default:
  paths: # input/output
    output: &output_path "vignettes/output"
  theme: "ggplot2::theme_bw() + ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))"
  colors:
    two:   &colors_two
      - "blue"
      - "red"
    three: &colors_three
      - "cyan"
      - "white"
      - "magenta"
    hex:   &colors_hex
      - "white"
      - "blue"
      - "yellow"
      - "red"
    many:  &colors_many
      - "#00FF00"
      - "#0000FF"
      - "#FF0000"
      - "#01FFFE"
      - "#FFA6FE"
      - "#FFDB66"
      - "#006401"
      - "#010067"
      - "#95003A"
      - "#007DB5"
      - "#FF00F6"
      - "#FFEEE8"
      - "#774D00"
      - "#90FB92"
      - "#0076FF"
      - "#D5FF00"
      - "#FF937E"
      - "#6A826C"
      - "#FF029D"
      - "#FE8900"
      - "#7A4782"
      - "#7E2DD2"
      - "#85A900"
      - "#FF0056"
      - "#A42400"
      - "#00AE7E"
      - "#683D3B"
      - "#BDC6FF"
      - "#263400"
      - "#BDD393"
      - "#00B917"
      - "#9E008E"
      - "#001544"
      - "#C28C9F"
      - "#FF74A3"
      - "#01D0FF"
      - "#004754"
      - "#E56FFE"
      - "#788231"
      - "#0E4CA1"
      - "#91D0CB"
      - "#BE9970"
      - "#968AE8"
      - "#BB8800"
      - "#43002C"
      - "#DEFF74"
      - "#00FFC6"
      - "#FFE502"
      - "#620E00"
      - "#008F9C"
      - "#98FF52"
      - "#7544B1"
      - "#B500FF"
      - "#00FF78"
      - "#FF6E41"
      - "#005F39"
      - "#6B6882"
      - "#5FAD4E"
      - "#A75740"
      - "#A5FFD2"
      - "#FFB167"
      - "#009BFF"
      - "#E85EBE"
  plot:
    path: *output_path
    type: "pdf"
    print_margin:         2 * 10
    major_width_A4: 297 - 2 * 10
    minor_width_A4: 210 - 2 * 10
    units:          "mm"
  distr: # default values for plot_distr_* functions
    regr:
      colors: *colors_hex
      metr:
        nbins: 50
      min_width: 0
      ylim: NULL
        #- 0.0
        #- 2.5e5
    class:
      colors: *colors_two
      metr:
        nbins: 20
        offset: 0.2
      min_width: 0
      ylim: NULL
    multiclass:
      colors: *colors_many
      metr:
        offset: 0.2
      min_width: 0.2
      ylim: NULL
